spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: on
server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
