spring:
  application:
    name: inventory-service

  # database connection:
  datasource:
    url: jdbc:h2:mem:product-db

  h2:
    console:
      enabled: true

  # rest repositories detection strategy:
  data:
    rest:
      detection-strategy: annotated

# server:
server:
  port: 8082

# register microservice with IP address:
eureka:
  instance:
    prefer-ip-address: true


